export const CONFIGURATION = {
  VERSION: "3.0.0",
  BANNED_ITEMS: [
    "minecraft:portal",
    "minecraft:item.soul_campfire",
    "minecraft:fire",
    "minecraft:item.chain",
    "minecraft:item.warped_door",
    "minecraft:item.crimson_door",
    "minecraft:item.campfire",
    "minecraft:item.kelp",
    "minecraft:bee_nest",
    "minecraft:beehive",
    "minecraft:item.wooden_door",
    "minecraft:item.iron_door",
    "minecraft:item.cake",
    "minecraft:item.reeds",
    "minecraft:item.camera",
    "minecraft:item.frame",
    "minecraft:pistonarmcollision",
    "minecraft:movingBlock",
    "minecraft:item.cake",
    "minecraft:item.flower_pot",
    "minecraft:info_update2",
    "minecraft:stickyPistonArmCollision",
    "minecraft:movingblock",
    "minecraft:invisiblebedrock",
    "minecraft:glowingobsidian",
    "minecraft:flowing_water",
    "minecraft:flowing_lava",
    "minecraft:item.nether_sprouts",
  ],
};
