export const CONFIGURATION = {
  VERSION: "2.0.0",
  BY_PASS_TAG: "staff",
  APPEAL_LINK: "https://discord.gg/dMa3A5UYKX",
  BANNED_ITEMS: [
    "minecraft:portal",
    "minecraft:item.soul_campfire",
    "minecraft:fire",
    "minecraft:item.chain",
    "minecraft:item.warped_door",
    "minecraft:item.crimson_door",
    "minecraft:item.campfire",
    "minecraft:item.kelp",
    "minecraft:bee_nest",
    "minecraft:beehive",
    "minecraft:item.wooden_door",
    "minecraft:item.iron_door",
    "minecraft:item.cake",
    "minecraft:item.reeds",
    "minecraft:item.camera",
    "minecraft:item.frame",
    "minecraft:pistonarmcollision",
    "minecraft:movingBlock",
    "minecraft:item.cake",
    "minecraft:item.flower_pot",
    "minecraft:info_update2",
    "minecraft:stickyPistonArmCollision",
    "minecraft:movingblock",
    "minecraft:moving_block",
    "minecraft:invisiblebedrock",
    "minecraft:glowingobsidian",
    "minecraft:flowing_water",
    "minecraft:flowing_lava",
    "minecraft:item.nether_sprouts",
    "minecraft:shield"
  ],
  BANNED_BLOCKS: [
    "minecraft:moving_block",
    "minecraft:beehive",
    "minecraft:beenest",
  ],
};
